version: '3'

services:
  bot:
    build:
      context: .
    environment:
      - BOT_TOKEN=6872236684:AAECovYGSLLHi_Rj8V3TDhLddAfF1CNxXcA
      - OMDB_API_KEY=aacba327
      - KINOPOISK_API_KEY=7QRYVD6-SDE4M47-JK6G372-QHZPD10
      - DATABASE_URL=sqlite+aiosqlite:///example.db
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
